# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI/Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(1153, 871)
        HomeWindow.setStyleSheet("")
        self.widget = QtWidgets.QWidget(HomeWindow)
        self.widget.setGeometry(QtCore.QRect(0, -30, 1201, 901))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.widget.setFont(font)
        self.widget.setStyleSheet("color:black;\n"
"\n"
"background-color: white;\n"
"\n"
"QDoubleSpinBox\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"color:black;\n"
"}\n"
"QDoubleSpinBox:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"}\n"
"QListWidget\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"color:black;\n"
"}\n"
"QListWidget:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"}\n"
"QListView{\n"
"background-color:  rgb(255, 255, 255);\n"
"  color: white;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:  rgb(200, 200, 200);\n"
"color:black;\n"
"}\n"
"QComboBox:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"}\n"
"\n"
"QTextBrowser\n"
"{\n"
"background-color: black;\n"
"color:white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 8px;\n"
"color:black;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"\n"
"color:balck;\n"
"}\n"
"QSpinBox:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel\n"
"{\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.load_image = QtWidgets.QPushButton(self.widget)
        self.load_image.setGeometry(QtCore.QRect(50, 830, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.load_image.setFont(font)
        self.load_image.setObjectName("load_image")
        self.image_slider = QtWidgets.QSlider(self.widget)
        self.image_slider.setGeometry(QtCore.QRect(270, 840, 781, 31))
        self.image_slider.setAcceptDrops(False)
        self.image_slider.setAutoFillBackground(False)
        self.image_slider.setMaximum(10)
        self.image_slider.setOrientation(QtCore.Qt.Horizontal)
        self.image_slider.setInvertedAppearance(False)
        self.image_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.image_slider.setTickInterval(0)
        self.image_slider.setObjectName("image_slider")
        self.detected_image_widget = QtWidgets.QWidget(self.widget)
        self.detected_image_widget.setGeometry(QtCore.QRect(160, 340, 831, 451))
        self.detected_image_widget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.detected_image_widget.setObjectName("detected_image_widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(610, 810, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.loaded_image_widget = QtWidgets.QWidget(self.widget)
        self.loaded_image_widget.setGeometry(QtCore.QRect(60, 100, 1031, 221))
        self.loaded_image_widget.setStyleSheet("QWidget\n"
"{\n"
"    background-color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.loaded_image_widget.setObjectName("loaded_image_widget")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(240, 70, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(540, 70, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(850, 70, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(480, 320, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 411, 20))
        font = QtGui.QFont()
        font.setFamily("Apple SD Gothic Neo")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "Form"))
        self.load_image.setText(_translate("HomeWindow", "Load Images"))
        self.label.setText(_translate("HomeWindow", "Image Number"))
        self.label_2.setText(_translate("HomeWindow", "Original Image"))
        self.label_3.setText(_translate("HomeWindow", "Detected Objects"))
        self.label_4.setText(_translate("HomeWindow", "Estimated Depths"))
        self.label_5.setText(_translate("HomeWindow", "Joint Object Detection and Depth Estimation"))
        self.label_6.setText(_translate("HomeWindow", "Deep Learning Project - Joint Depth Estimation and Object Detection"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWindow = QtWidgets.QWidget()
    ui = Ui_HomeWindow()
    ui.setupUi(HomeWindow)
    HomeWindow.show()
    sys.exit(app.exec_())
