# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Home.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomeWindow(object):
    def setupUi(self, HomeWindow):
        HomeWindow.setObjectName("HomeWindow")
        HomeWindow.resize(767, 646)
        HomeWindow.setStyleSheet("QWidget\n"
"{\n"
"background : white;\n"
"}")
        self.widget = QtWidgets.QWidget(HomeWindow)
        self.widget.setGeometry(QtCore.QRect(0, 0, 761, 641))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.widget.setFont(font)
        self.widget.setStyleSheet("color:black;\n"
"\n"
"\n"
"\n"
"QDoubleSpinBox\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"color:black;\n"
"}\n"
"QDoubleSpinBox:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"}\n"
"QListWidget\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"color:black;\n"
"}\n"
"QListWidget:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"}\n"
"QListView{\n"
"background-color:  rgb(255, 255, 255);\n"
"  color: white;\n"
"}\n"
"\n"
"QComboBox{\n"
"background-color:  rgb(200, 200, 200);\n"
"color:black;\n"
"}\n"
"QComboBox:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"}\n"
"\n"
"QTextBrowser\n"
"{\n"
"background-color: black;\n"
"color:white;\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"border-radius: 8px;\n"
"color:black;\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"QSpinBox\n"
"{\n"
"background-color: rgb(200, 200, 200);\n"
"\n"
"color:balck;\n"
"}\n"
"QSpinBox:hover {\n"
"  background-color:  rgb(166, 166, 166);\n"
"  color: white;\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"QLabel\n"
"{\n"
"color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.widget.setObjectName("widget")
        self.load_image = QtWidgets.QPushButton(self.widget)
        self.load_image.setGeometry(QtCore.QRect(70, 50, 113, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.load_image.setFont(font)
        self.load_image.setObjectName("load_image")
        self.loaded_image_plot = QtWidgets.QWidget(self.widget)
        self.loaded_image_plot.setGeometry(QtCore.QRect(430, 10, 291, 271))
        self.loaded_image_plot.setStyleSheet("QWidget\n"
"{\n"
"    background-color: white;\n"
"}\n"
"\n"
"\n"
"")
        self.loaded_image_plot.setObjectName("loaded_image_plot")

        self.retranslateUi(HomeWindow)
        QtCore.QMetaObject.connectSlotsByName(HomeWindow)

    def retranslateUi(self, HomeWindow):
        _translate = QtCore.QCoreApplication.translate
        HomeWindow.setWindowTitle(_translate("HomeWindow", "Form"))
        self.load_image.setText(_translate("HomeWindow", "Load Image"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HomeWindow = QtWidgets.QWidget()
    ui = Ui_HomeWindow()
    ui.setupUi(HomeWindow)
    HomeWindow.show()
    sys.exit(app.exec_())
